apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ name }}-rule
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: websites-watcher-{{ name }}-virtual-service
    app.kubernetes.io/part-of: websites-watcher
    app.kubernetes.io/component: core
spec:
  exportTo:
    - "."
  hosts:
    - {{ host }}
  gateways:
    - mesh
    - {{ namespace }}/websites-watcher-egress-gateway
  http:
      - match:
        - gateways:
            - mesh
          port: 80
        route:
          - destination:
              host: websites-watcher-egressgw.{{ namespace }}.svc.cluster.local
              subset: {{ name }}
              port:
                number: 80
      - match:
          - gateways:
              - {{ namespace }}/websites-watcher-egress-gateway
            port: 80
        route:
          - destination:
              host: {{ host }}
              port:
                number: {{ ext_https_port }}