apiVersion: v1
kind: Service
metadata:
  name: websites-watcher-core-service
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: websites-watcher-core-service
    app.kubernetes.io/part-of: websites-watcher
    app.kubernetes.io/component: core
spec:
  selector:
    app: websites-watcher-core
  ports:
    - name: http-rest-api
      protocol: TCP
      port: 8080
      targetPort: core-rest-api
    - name: http-actuator
      protocol: TCP
      port: 8081
      targetPort: core-actuator