spring:
  application:
    name: Websites Watcher
    version: @revision@
  mvc:
    problemdetails:
      enabled: true

server:
  servlet:
    encoding:
      force: true

app:
  watchers:
    ru-web:
      cron: "0 0/1 * * * *"
      url: https://ruweb.net/vps-europe/netherlands
      plan-name: KVMe-NANO