logging:
  level:
    root: ${ROOT_LOG_LEVEL}

app:
  common:
    chrome-driver-path: ${CHROME_DRIVER_PATH}
  watchers:
    ru-web:
      cron: ${RU_WEB_CRON}
      url: ${RU_WEB_URL}
      plan-name: ${RU_WEB_PLAN_NAME}