logging:
  level:
    root: ${ROOT_LOG_LEVEL}

app:
  common:
    chrome-driver-path: ${CHROME_DRIVER_PATH}
    remote-chrome-selenium-url: ${REMOTE_CHROME_SELENIUM_URL}
  watchers:
    ru-web:
      cron: ${RU_WEB_CRON}
      url: ${RU_WEB_URL}
      plan-name: ${RU_WEB_PLAN_NAME}
      send-negative-notifications: ${RU_WEB_SEND_NEGATIVE_NOTIFICATIONS:false}
  telegram:
    api:
      rest-api-base-url: ${TELEGRAM_BOT_REST_BASE_URL}
      api-token: ${TELEGRAM_BOT_TOKEN}
      request-timeout-ms: ${TELEGRAM_BOT_API_REQUEST_TIMEOUT_MS}
      max-retries: ${TELEGRAM_BOT_API_REQUEST_MAX_RETRIES}
      notifications-chat-id: ${TELEGRAM_BOT_NOTIFICATIONS_CHAT_ID}